#!/bin/bash

# Copy this script to the assembly that you want to analyze in 03.sqanti
echo 'analysis for flair' >> sqanti_summary.txt
wc -l *flair.*classification.txt | awk '{print "transcripts assembled: " $1 -1}' >> sqanti_summary.txt # no. of transcripts (-1 for the header line)
grep 'full-splice_match' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "FSM:\t" $1}' >> sqanti_summary.txt #for unique fsm
grep 'full-splice_match' *flair.*classification.txt | grep -e 'reference_match' -e 'mono-exon' | cut -f8 | uniq | wc -l | awk '{print "RM:\t" $1}' >> sqanti_summary.txt #for unique rm
grep 'incomplete-splice_match' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "ISM:\t" $1}' >> sqanti_summary.txt #for unique ism
grep 'novel_in_catalog' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NIC:\t" $1}' >> sqanti_summary.txt # for unique NIC
grep 'novel_not_in_catalog' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NNC:\t" $1}' >> sqanti_summary.txt # for unique NNC
grep 'antisense' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "antisense:\t" $1}'>> sqanti_summary.txt # for unique antisense
grep 'genic' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "genic:\t" $1}' >> sqanti_summary.txt # for unique genic
grep 'intergenic' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "intergenic:\t" $1}' >> sqanti_summary.txt # for unique intergenic
grep 'fusion' *flair.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "fusion:\t" $1}' >> sqanti_summary.txt # for unique fusion

echo 'analysis for stringtie.guided' >> sqanti_summary.txt
wc -l *stringtie.guided.*classification.txt | awk '{print "transcripts assembled: " $1 -1}' >> sqanti_summary.txt # no. of transcripts (-1 for the header line)
grep 'full-splice_match' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "FSM:\t" $1}' >> sqanti_summary.txt #for unique fsm
grep 'full-splice_match' *stringtie.guided.*classification.txt | grep -e 'reference_match' -e 'mono-exon' | cut -f8 | uniq | wc -l | awk '{print "RM:\t" $1}' >> sqanti_summary.txt #for unique rm
grep 'incomplete-splice_match' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "ISM:\t" $1}' >> sqanti_summary.txt #for unique ism
grep 'novel_in_catalog' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NIC:\t" $1}' >> sqanti_summary.txt # for unique NIC
grep 'novel_not_in_catalog' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NNC:\t" $1}' >> sqanti_summary.txt # for unique NNC
grep 'antisense' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "antisense:\t" $1}'>> sqanti_summary.txt # for unique antisense
grep 'genic' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "genic:\t" $1}' >> sqanti_summary.txt # for unique genic
grep 'intergenic' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "intergenic:\t" $1}' >> sqanti_summary.txt # for unique intergenic
grep 'fusion' *stringtie.guided.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "fusion:\t" $1}' >> sqanti_summary.txt # for unique fusion

echo 'analysis for rb' >> sqanti_summary.txt
wc -l *rb.*classification.txt | awk '{print "transcripts assembled: " $1 -1}' >> sqanti_summary.txt # no. of transcripts (-1 for the header line)
grep 'full-splice_match' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "FSM:\t" $1}' >> sqanti_summary.txt #for unique fsm
grep 'full-splice_match' *rb.*classification.txt | grep -e 'reference_match' -e 'mono-exon' | cut -f8 | uniq | wc -l | awk '{print "RM:\t" $1}' >> sqanti_summary.txt #for unique rm
grep 'incomplete-splice_match' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "ISM:\t" $1}' >> sqanti_summary.txt #for unique ism
grep 'novel_in_catalog' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NIC:\t" $1}' >> sqanti_summary.txt # for unique NIC
grep 'novel_not_in_catalog' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NNC:\t" $1}' >> sqanti_summary.txt # for unique NNC
grep 'antisense' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "antisense:\t" $1}'>> sqanti_summary.txt # for unique antisense
grep 'genic' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "genic:\t" $1}' >> sqanti_summary.txt # for unique genic
grep 'intergenic' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "intergenic:\t" $1}' >> sqanti_summary.txt # for unique intergenic
grep 'fusion' *rb.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "fusion:\t" $1}' >> sqanti_summary.txt # for unique fusion

echo 'analysis for stringtie.free' >> sqanti_summary.txt
wc -l *stringtie.free.*classification.txt | awk '{print "transcripts assembled: " $1 -1}' >> sqanti_summary.txt # no. of transcripts (-1 for the header line)
grep 'full-splice_match' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "FSM:\t" $1}' >> sqanti_summary.txt #for unique fsm
grep 'full-splice_match' *stringtie.free.*classification.txt | grep -e 'reference_match' -e 'mono-exon' | cut -f8 | uniq | wc -l | awk '{print "RM:\t" $1}' >> sqanti_summary.txt #for unique rm
grep 'incomplete-splice_match' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "ISM:\t" $1}' >> sqanti_summary.txt #for unique ism
grep 'novel_in_catalog' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NIC:\t" $1}' >> sqanti_summary.txt # for unique NIC
grep 'novel_not_in_catalog' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "NNC:\t" $1}' >> sqanti_summary.txt # for unique NNC
grep 'antisense' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "antisense:\t" $1}'>> sqanti_summary.txt # for unique antisense
grep 'genic' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "genic:\t" $1}' >> sqanti_summary.txt # for unique genic
grep 'intergenic' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "intergenic:\t" $1}' >> sqanti_summary.txt # for unique intergenic
grep 'fusion' *stringtie.free.*classification.txt | cut -f8 | uniq | wc -l | awk '{print "fusion:\t" $1}' >> sqanti_summary.txt # for unique fusion